name: Deploy Discord Bot

on:
  push:
    branches:
      - main
  schedule:
    - cron: '58 */5 * * *'  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Node.js
        run: |
          curl -fsSL https://deb.nodesource.com/setup_20.x | sudo -E bash -
          sudo apt-get install -y nodejs

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'

      - name: Run node 20
        run: |
         runs:
         using: 'node20'
         main: 'web_app.py'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install discord.py python-dotenv Flask

      - name: Run the bot and Flask API
        env:
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
          DISCORD_GUILD_ID: ${{ secrets.DISCORD_GUILD_ID }}
          SPOTIFY_CLIENT_ID: ${{ secrets.SPOTIFY_CLIENT_ID }}
          SPOTIFY_CLIENT_SECRET: ${{ secrets.SPOTIFY_CLIENT_SECRET }}
          SPOTIFY_REDIRECT_URI: ${{ secrets.SPOTIFY_REDIRECT_URI }}
        run: |
          while true; do
            python bot.py & python web_app.py
            sleep 21480 
          done
