version: '3'
services:
  discord_bot:
    image: python:3.9
    volumes:
      - .:/bot
    working_dir: /bot
    environment:
      - DISCORD_TOKEN=${{ secrets.DISCORD_TOKEN }}
      - DISCORD_GUILD_ID=${{ secrets.DISCORD_GUILD_ID }}
    command: python bot.py
